import { omit } from "lodash";
import { DocumentDefinition, FilterQuery } from "mongoose";
import IUserModel from "../interfaces/IUserModel";
import UserModel from "../models/UserModel";

export async function createUser(
	// Document Definition is a generic type, so we pass our UserModel Interface
	input: DocumentDefinition<
		// omit the properties that are generated by mongoose and not part of the request 
		Omit<IUserModel, "createdAt" | "updatedAt" | "comparePassword">
	>
) {
	try {
		// create a new user with the userModel
		const user = await UserModel.create(input);
		return omit(user.toJSON(), ["password"]);
	} catch (err: any) {
		throw new Error(err);
	}
}

// check password, if correct return user object else return false
export async function validatePassword({
	email,
	password
}: {
	email: string;
	password: string;
}) {
	// search for user by their email address
	const user = await UserModel.findOne({ email });

	// the user doesn't exist
	if (!user) {
		return false;
	}

	// if the user does exist, validate the password
	const isValid = await user.comparePassword(password);

	// if the password isn't valid
	if (!isValid) {
		return false;
	}

	// return the user, omitting the password
	return omit(user.toJSON(), ['password']);
}

// find a user
export async function findUser(query: FilterQuery<IUserModel>) {
	return UserModel.findOne(query).lean()
}
